### ISSUE TITLE
用于获取json数据的api失效，番茄悄咪咪更新了

### ISSUE THREAD

**Issue by Kovio1** [zhousanfu/story-vision#1]
大佬，txt.py里面的用于获取json数据的link = f'https://novel.snssdk.com/api/novel/channel/homepage/search/search/v1/?device_platform=android&parent_enterfrom=novel_channel_search.tab.&aid=1976&platform_id=1&group_id={chapter_id}&item_id={chapter_id}'，这个api失效了，获取不了数据，能更新一下吗？

**Comment by zhousanfu** [comment]
修复了, https://github.com/zhousanfu/story-vision/blob/main/txt.py

**Comment by Kovio1** [comment]
成功跑起来了，谢谢大佬
